services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'

  backend:
    build:
      context: ./backend/soboksobok
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - './backend/soboksobok/:/app'
      - '/app/node_modules'

